# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict, Field

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (2)
# #########################################################################

class InvoiceExtraction(BaseModel):
    invoice_number: typing.Optional[str] = None
    date: typing.Optional[str] = None
    vendor_name: typing.Optional[str] = None
    subtotal: typing.Optional[str] = None
    tax: typing.Optional[str] = None
    total_amount: typing.Optional[str] = None
    line_items: typing.Optional[typing.List["LineItem"]] = None

class LineItem(BaseModel):
    description: typing.Optional[str] = None
    quantity: typing.Optional[str] = None
    unit_price: typing.Optional[str] = None
    total: typing.Optional[str] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
