# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict, Field


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (0)
# #########################################################################

# #########################################################################
# Generated classes (2)
# #########################################################################

class InvoiceExtraction(BaseModel):
    invoice_number: typing.Optional[str] = None
    date: typing.Optional[str] = None
    vendor_name: typing.Optional[str] = None
    subtotal: typing.Optional[str] = None
    tax: typing.Optional[str] = None
    total_amount: typing.Optional[str] = None
    line_items: typing.Optional[typing.List["LineItem"]] = None

class LineItem(BaseModel):
    description: typing.Optional[str] = None
    quantity: typing.Optional[str] = None
    unit_price: typing.Optional[str] = None
    total: typing.Optional[str] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
